name: 同步nvjdcdocker仓库
on:
  schedule:
    - cron: '48 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-NolanHzy-nvjdcdocker
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync NolanHzy-nvjdcdocker
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/NolanHzy/nvjdcdocker.git"
          source_branch: "main"
          destination_branch: "NolanHzy"
          github_token: ${{ secrets.PAT }}
