name: sync-xmly_Action
on:
  schedule:
    - cron: '12 */12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-xuzijia2008-xmly_Action
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync xuzijia2008-xmly_Action
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/xuzijia2008/xmly_Action.git"
          source_branch: "main"
          destination_branch: "xmly"
          github_token: ${{ secrets.PAT }}
